config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :posts do
    resources :comments, only: %i[create edit update destroy]
  end


  root "posts#index"
  get '/my', to: 'posts#user_post'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_one_attached :attachment, dependent: :destroy

  validates :title, :body, presence: true

  validates :attachment, content_type: { in: ['image/png', 'image/jpeg', 'image/jpg'], message: 'must be a JPEG, PNG or JPG' },
                         size: { less_than: 5.megabytes, message: 'image is too large, max size 1 image - 5MB' }

  def self.user_posts(user)
    where('user_id = ?', user.id)
  end

  def self.index_post
    @posts = Post.where(is_active: true).order(created_at: :desc).page params[:page]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[create update destroy edit new]
  before_action :set_comment, only: %i[edit update destroy]
  before_action :set_post, only: %i[create destroy edit update]

  def new
    @comment = Comment.new
  end

  def edit; end

  def create
    @comment = @post.comments.new(comment_params.merge(user: current_user))

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = @comment.post
    @comment.update(comment_params)
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy

    flash[:good] = 'Comment deleted successfully.'
    redirect_to @post
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create update destroy edit new]
  before_action :load_post, only: %i[show edit update destroy]

  def index
    public_post
  end

  def user_post
    user = current_user
    @posts = Post.user_posts(user)
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    flash[:good] = 'Post deleted successfully.'
    redirect_to root_path
  end

  private

  def load_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :attachment)
  end

  def public_post
    @posts = Post.where(is_active: true).order(created_at: :desc).page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<% @post.comments.each do |comment| %>
  <div class="comments>
  <hr>
    <div class="card">
      <div class="card-body">
        <p class="mt-1">
          <%= comment.body %>
          <br>
          <%= comment.user.email %>
        </p>
        <br>
        <% if user_signed_in? %>
          <div class="small float-start pt-1">
            <%= link_to 'Edit comment', edit_post_comment_path(@post, comment), class: 'btn btn-info btn-sm' %>
            <%= link_to 'Delete comment', post_comment_path(@post, comment), data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm' %>
          </div>
        <% end %>
      </div>
    </div>
  <br>
  <hr>
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <div class="comment-errors">
    <%= render 'shared/errors', resource: @comment %>
  </div>
    <%= form_with model: [@post, @post.comments.new], id: 'new-comment' do |f| %>
      <div class="form-floating">
        <%= f.text_area :body, class: "form-control", placeholder: "Leave a comment here", id: "floatingTextarea" %>
        <label for="floatingTextarea">Leave a comment here</label>
        <div class="float-start mt-2 pt-1">
          <%= f.submit 'Create comment', class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
<% end %>

app/views/comments/edit.html.erb
<div class="form_comment">
  <div class="comment-errors">
    <%= render 'shared/errors', resource: @comment %>
  </div>
  <%= form_with model: [@post, @comment] do |f| %>
    <div class="form-floating">
      <%= f.text_area :body, class: "form-control", placeholder: "Leave a comment here", id: "floatingTextarea" %>
      <label for="floatingTextarea">Leave a comment here</label>
      <div class="float-start mt-2 pt-1">
        <%= f.submit 'Update comment', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
  <br><br><br>
  <%= link_to 'Back to post', post_path(@post), class: 'btn btn-info btn-sm' %>
</div>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class ="container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="post_content">
  <% if user_signed_in? %>
    <div class="container">
      <div class="row d-flex justify-content-center align-items-center">
        <div class="col-12 col-md-9 col-lg-7 col-xl-9">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create post</h2>

                <%= form_with model: @post do |f| %>
                <div class="post-errors">
                  <%= render 'shared/errors', resource: @post %>
                </div>
                <div class="mb-5">
                  <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
                </div>

                <div class="mb-5">
                  <%= f.text_area :body, class: "form-control", placeholder: "Body" %>
                </div>

                <div class="input-group mb-5">
                  <label class="input-group-text" for="inputGroupAttachment">Upload foto</label>
                  <%= f.file_field :attachment, class: "form-control", id: "inputGroupAttachment"%>
                </div>

                <div class="d-grid gap-2">
                  <%= f.submit "Create post", class: 'btn btn-info btn-lg' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<br>
<% if user_signed_in? %>
  <%= link_to "My post", my_path, class: 'btn btn-info btn-sm' %>
<% end %>
<br>
<% @posts.each do |post| %>
  <%= link_to post_path(post) do %>
    <li><%= post.title %></li>
  <% end %>
<% end %>
<div class="pagination"><%= paginate @posts %></div>

app/views/posts/show.html.erb
<div class="post-errors">
  <%= render 'shared/errors', resource: @post %>
</div>

<div class="title_header">
  <div class="title">
    <h2><%= @post.title %></h2>
  </div>
  <div class="foto">
    <% if @post.attachment.attached? %>
      <%= image_tag url_for(@post.attachment), class: "img" %>
    <% end %>
  </div>
</div>
<hr>
<% if user_signed_in? %>
  <div class="float-end pt-1">
    <%= link_to 'Edit post', edit_post_path(@post), class: 'btn btn-info btn-sm' %>
    <%= link_to 'Delete post', post_path(@post), data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm' %>
  </div>
<% end %>
<br>
<div class="body">
  <%= @post.body %>
</div>
<br><br>
<h3>Comments</h3>
<div class="comments">
  <%= render 'comments/comments' %>
  <%= render 'comments/form' %>
</div>

app/views/posts/user_post.html.erb
<br>
<% if user_signed_in? %>
  <%= link_to "All post", root_path, class: 'btn btn-info btn-sm' %>
<br>
  <% @posts.each do |post| %>
    <%= link_to post_path(post) do %>
      <% if post.is_active? %>
        <li><%= post.title %></li>
      <% else %>
        <li><%= post.title %> - not active!</li>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_errors.html.erb
<% if resource&.errors.present? %>
  <div class="alert alert-danger" role="alert">
    <%= "#{resource.errors.count} error(s) detected: " %>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
    <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :div, message, class: "alert alert-success mt-3 alert-#{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-3 my-4">
  <p class="text-center text-muted">© Blog</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark" style="background-color: #4474af">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
           <li class="nav-item active">
            <li class="nav-item">
              <a class="nav-link active" href="<%= destroy_user_session_path %>">Log out</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="<%= new_post_path %>">Create post</a>
            </li>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link active" href="<%= new_user_session_path %>">Log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="<%= new_user_registration_path %>">Sign up</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>